pipeline:
  name: mower front
  identifier: mower_front
  tags: {}
  template:
    templateRef: account.npm_pipeline
    versionLabel: v0.1
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: account.Github
            repoName: stfgit/mower-frontend
            build:
              spec:
                branch: main
              type: branch
      stages:
        - stage:
            identifier: scan_sources
            template:
              templateInputs:
                type: SecurityTests
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.k8sdocacloud
                      namespace: harness-ci
                  execution:
                    steps:
                      - parallel:
                          - step:
                              identifier: owasp
                              type: Owasp
                              spec:
                                advanced:
                                  fail_on_severity: none
                                resources:
                                  limits:
                                    memory: <+input>.default(2Gi)
                                    cpu: <+input>.default(500m)
                          - step:
                              identifier: aquatrivy
                              type: AquaTrivy
                              spec:
                                advanced:
                                  fail_on_severity: none
                                resources:
                                  limits:
                                    memory: ""
                                    cpu: ""
                          - step:
                              identifier: gitleaks
                              type: Gitleaks
                              spec:
                                advanced:
                                  fail_on_severity: low
                                resources:
                                  limits:
                                    memory: ""
                                    cpu: ""
                delegateSelectors:
                  - ""
        - stage:
            identifier: npm_build_and_push
            template:
              templateInputs:
                type: CI
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.k8sdocacloud
                      namespace: harness-ci
                  execution:
                    steps:
                      - step:
                          identifier: Install_Dependencies
                          type: Run
                          spec:
                            connectorRef: org.Dockerhub
                            image: node:20
                      - step:
                          identifier: ESLint_Check
                          type: Run
                          spec:
                            connectorRef: org.Dockerhub
                            image: node:20
                      - step:
                          identifier: Build_Application
                          type: Run
                          spec:
                            connectorRef: org.Dockerhub
                            image: node:20
                      - step:
                          identifier: Unit_Tests
                          type: Run
                          spec:
                            connectorRef: org.Dockerhub
                            image: node:20
                      - step:
                          identifier: NPM_Audit
                          type: Run
                          spec:
                            connectorRef: org.Dockerhub
                            image: node:20
                      - step:
                          identifier: BuildAndPushDockerRegistry_1
                          type: BuildAndPushDockerRegistry
                          spec:
                            connectorRef: org.Dockerhub
                            repo: stfgit/mower-frontend
        - stage:
            identifier: scan_images
            template:
              templateInputs:
                type: SecurityTests
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.k8sdocacloud
                      namespace: harness-ci
                  execution:
                    steps:
                      - step:
                          identifier: aquatrivy_container
                          type: AquaTrivy
                          spec:
                            advanced:
                              fail_on_severity: none
                            resources:
                              limits:
                                memory: ""
                                cpu: ""
                            image:
                              type: docker_v2
                              name: <+input>
                delegateSelectors: <+input>
        - stage:
            identifier: deploy
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: development
                    infrastructureDefinitions:
                      - identifier: infra_dev
                    gitBranch: main
                  service:
                    serviceRef: mower_frontend_service
                    serviceInputs:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          artifacts:
                            primary:
                              sources:
                                - identifier: frontendImage
                                  type: DockerRegistry
                                  spec:
                                    tag: latest
                delegateSelectors:
                  - helm-delegate
        - stage:
            identifier: mep_approval
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: approval
                          type: HarnessApproval
                          spec:
                            approvers:
                              minimumCount: <+input>.default(1)
                              userGroups:
                                - org.DevOps_Team
                delegateSelectors: <+input>
        - stage:
            identifier: deploy_prod
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: prod
                    infrastructureDefinitions:
                      - identifier: mower_infra
                delegateSelectors:
                  - helm-delegate
  projectIdentifier: Mower
  orgIdentifier: stf
